name: Trigger Test

on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types:
      - completed

jobs:
  test-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Test Trigger
        run: echo "Trigger test workflow ran successfully!"
